### ISSUE TITLE
Revisione pkgbuild

### ISSUE THREAD

**Issue by FabioLolix** [ArchItalia/clean#1]
Ciao Jonathan, ti ho revisionato i pkgbuild per la versione stabile e git come si deve

[PKGBUILD-stable.txt](https://github.com/ArchItalia/clean/files/12004839/PKGBUILD-stable.txt)

[PKGBUILD-git.txt](https://github.com/ArchItalia/clean/files/12004840/PKGBUILD-git.txt)

**Comment by ArchItalia** [comment]
grazie spero di aver fatto bene.
