### ISSUE TITLE
improved search for junk files

### ISSUE THREAD

**Issue by Wjxfi** [ArchItalia/clean#2]
I tried to install stable diffusion via arm and when all about 30 gb were downloaded I got an error because I had intel. everything I downloaded was not deleted after the error and I don't know how to delete it. Can you help clean up my trash dozens of gigabytes?

**Comment by ArchItalia** [comment]
This script is responsible for keeping the Arch Linux system clean from obsolete files and other types of files. Here's what it does:

- remove files from the path ~/.local/share/Trash/files/*
- remove files from the path ~/.cache/*
- remove orphan installed packages
- remove installed dependencies that are not used by any active package 
- remove cache of packages that have been removed from the system 
- remove all cache of packages that have been removed and installed in the system 

However, Clean does not deal with user-caused errors for poor management or files downloaded in the user's home directory that may have different write and read permissions. Additionally, we do not appreciate opening an issue for a strictly personal and irrelevant reason for this script. We encourage you to read the wiki and manual for the proper use of the Arch Linux system. Goodbye.
